context("OptimizerGenSA")

test_that("OptimizerGenSA", {
  opt = OptimizerGenSA$new()
  expect_class(opt, "Optimizer")
  expect_class(opt, "OptimizerGenSA")
  expect_output(print(opt), "OptimizerGenSA")
  inst = MAKE_INST()
  opt$optimize(inst)
  expect_data_table(inst$result)
  expect_number(inst$result_y)
  expect_equal(names(inst$result_y), inst$objective$codomain$ids())
  expect_list(inst$result_x_domain)
  expect_equal(names(inst$result_x_domain), setdiff(inst$objective$domain$ids(), "foo"))
  expect_equal(inst$result_y, unlist(inst$objective$eval(inst$result_x_domain)["y"]))
})
