#' @title Optimization via Local Search
#'
#' @include Optimizer.R
#' @name mlr_optimizers_local_search
#'
#' @description
#' `OptimizerBatchLocalSearch` class that implements a simple Local Search.
#' Local Search starts by determining the `n_initial_points` initial best points present in the [Archive] of the [OptimInstance].
#' If fewer points than `n_initial_points` are present, additional `initial_random_sample_size` points sampled uniformly at random are evaluated and the best `n_initial_points` initial points are determined.
#'
#' In each iteration, for each of the `n_initial_points` initial best points, `neighbors_per_point` neighbors are generated by local mutation.
#' Local mutation generates a neighbor by sampling a single parameter that is to be mutated and then proceeds as follows: Double parameters ([paradox::p_dbl()]) are mutated via Gaussian mutation (with a prior standardization to `[0, 1]` and retransformation after mutation).
#' Integer parameters ([paradox::p_int()]) undergo the same mutation but are rounded to the closest integer after mutation.
#' Categorical parameters ([paradox::p_fct()] and [paradox::p_lgl()]) are mutated via uniform mutation.
#' Note that parameters that are conditioned on (i.e., they are parents of a [paradox::Condition], see the dependencies of the search space) are not mutated.
#'
#' @templateVar id local_search
#' @template section_dictionary_optimizers
#'
#' @section Parameters:
#' \describe{
#' \item{`n_initial_points`}{`integer(1)`\cr
#'   Size of the set of initial best points which are used as starting points for the Local Search.
#'   Default is `10`.}
#' \item{`initial_random_sample_size`}{`integer(1)`\cr
#'   Number of points that are sampled uniformly at random before the best `n_initial_points` initial points are determined, if fewer points than `n_initial_points` are present in the [Archive] of the [OptimInstance].
#'   Default is `100`.}
#' \item{`neighbors_per_point`}{`integer(1)`\cr
#'   Number of neighboring points to generate for each of the `n_initial_points` best starting points in each iteration.
#'   Default is `100`.}
#' \item{`mutation_sd`}{`numeric(1)`\cr
#'   Standard deviation used to create neighbors during mutation of numeric parameters on the standardized `[0, 1]` scale.
#'   Default is `0.1`.}
#' }
#'
#' @section Archive:
#' The [bbotk::Archive] holds the following additional column that is specific to the algorithm:
#'   * `.point_id` (`integer(1)`)\cr
#'     The id (`1, ..., n_initial_points`) indicating from which of the `n_initial_points` best points the evaluated point was generated from.
#'
#' @template section_progress_bars
#'
#' @export
#' @examples
#' search_space = domain = ps(x = p_dbl(lower = -1, upper = 1))
#'
#' codomain = ps(y = p_dbl(tags = "minimize"))
#'
#' objective_function = function(xs) {
#'   list(y = as.numeric(xs)^2)
#' }
#'
#' objective = ObjectiveRFun$new(
#'  fun = objective_function,
#'  domain = domain,
#'  codomain = codomain)
#'
#' instance = OptimInstanceBatchSingleCrit$new(
#'  objective = objective,
#'  search_space = search_space,
#'  terminator = trm("evals", n_evals = 100))
#'
#' # evaluate an initial sample of 10 points uniformly at random
#' # choose the best 3 points as the initial points
#' # for each of these points generate 10 neighbors
#' # repeat this process
#' optimizer = opt("local_search",
#'   n_initial_points = 3,
#'   initial_random_sample_size = 10,
#'   neighbors_per_point = 10)
#'
#' # modifies the instance by reference
#' optimizer$optimize(instance)
#'
#' # returns best scoring evaluation
#' instance$result
#'
#' # allows access of data.table of full path of all evaluations
#' as.data.table(instance$archive$data)
OptimizerBatchLocalSearch2 = R6Class("OptimizerBatchLocalSearch2",
  inherit = bbotk::OptimizerBatch,
  public = list(

    #' @description
    #' Creates a new instance of this [R6][R6::R6Class] class.
    initialize = function() {
      param_set = ps(
        n_searches = p_int(lower = 1L, default = 10L),
        n_steps = p_int(lower = 1L, default = 10L),
        n_neighbors = p_int(lower = 1L, default = 100L),
        mut_sd = p_dbl(lower = 0L, default = 0.1)
      )
      param_set$values = list(n_searches = 10L, n_steps = 10L, n_neighbors = 100L, mut_sd = 0.1)

      super$initialize(
        id = "local_search_2",
        param_set = param_set,
        param_classes = c("ParamLgl", "ParamInt", "ParamDbl", "ParamFct"),
        properties = c("dependencies", "single-crit"),   # FIXME: we cannot handle deps?
        label = "Local Search",
        man = "bbotk::mlr_optimizers_local_search"
      )
    }
  ),
  private = list(
    .optimize = function(inst) {
      ps = self$param_set
      psv = ps$values
      
      control = self$param_set$values
      control$obj_mult = inst$objective_multiplicator
      .Call("c_local_search", inst$search_space, control, inst, PACKAGE = "bbotk")
    }
  )
)

mlr_optimizers$add("local_search_2", OptimizerBatchLocalSearch2)
