#' @title Optimization via Local Search
#'
#' @include Optimizer.R
#' @name mlr_optimizers_local_search
#'
#' @description
#' `OptimizerBatchLocalSearch` class that implements a simple Local Search.
#' Local Search starts a series of `n_searches` searches.
#' In each search, a start point is sampled uniformly at random from the search space.
#' For each of these points, `n_neighbors` neighbors are generated by local mutation.
#' The points are evaluated and the best point of each search is the next start point.
#' Each search is repeated for `n_steps` steps.
#'
#' Local mutation generates a neighbor by sampling a single parameter that is to be mutated and then proceeds as follows: Double parameters ([paradox::p_dbl()]) are mutated via Gaussian mutation (with a prior standardization to `[0, 1]` and retransformation after mutation).
#' Integer parameters ([paradox::p_int()]) undergo the same mutation but are rounded to the closest integer after mutation.
#' Categorical parameters ([paradox::p_fct()] and [paradox::p_lgl()]) are mutated via uniform mutation.
#' Note that parameters that are conditioned on (i.e., they are parents of a [paradox::Condition], see the dependencies of the search space) are not mutated.
#'
#' @templateVar id local_search
#' @template section_dictionary_optimizers
#'
#' @section Parameters:
#' \describe{
#' \item{`n_searches`}{`integer(1)`\cr
#'   Number of local searches to perform.
#'   Default is `10`.}
#' \item{`n_steps`}{`integer(1)`\cr
#'   Number of steps to perform for each search.
#'   Default is `10`.}
#' \item{`n_neighbors`}{`integer(1)`\cr
#'   Number of neighbors to generate in each step.
#'   Default is `100`.}
#' \item{`mut_sd`}{`numeric(1)`\cr
#'   Standard deviation used to create neighbors during mutation of numeric parameters on the standardized `[0, 1]` scale.
#'   Default is `0.1`.}
#' }
#'
#' @template section_progress_bars
#'
#' @export
#' @examples
#' search_space = domain = ps(x = p_dbl(lower = -1, upper = 1))
#'
#' codomain = ps(y = p_dbl(tags = "minimize"))
#'
#' objective_function = function(xs) {
#'   list(y = as.numeric(xs)^2)
#' }
#'
#' objective = ObjectiveRFun$new(
#'  fun = objective_function,
#'  domain = domain,
#'  codomain = codomain)
#'
#' instance = OptimInstanceBatchSingleCrit$new(
#'  objective = objective,
#'  search_space = search_space,
#'  terminator = trm("evals", n_evals = 100))
#'
#' # evaluate an initial sample of 10 points uniformly at random
#' # choose the best 3 points as the initial points
#' # for each of these points generate 10 neighbors
#' # repeat this process
#' optimizer = opt("local_search",
#'   n_searches = 3,
#'   n_steps = 10,
#'   n_neighbors = 100,
#'   mut_sd = 0.1)
#'
#' # modifies the instance by reference
#' optimizer$optimize(instance)
#'
#' # returns best scoring evaluation
#' instance$result
#'
#' # allows access of data.table of full path of all evaluations
#' as.data.table(instance$archive$data)
OptimizerBatchLocalSearch = R6Class("OptimizerBatchLocalSearch",
  inherit = bbotk::OptimizerBatch,
  public = list(

    #' @description
    #' Creates a new instance of this [R6][R6::R6Class] class.
    initialize = function() {
      param_set = ps(
        n_searches = p_int(lower = 1L, default = 10L),
        n_steps = p_int(lower = 1L, default = 10L),
        n_neighbors = p_int(lower = 1L, default = 100L),
        mut_sd = p_dbl(lower = 0L, default = 0.1)
      )
      param_set$values = list(n_searches = 10L, n_steps = 10L, n_neighbors = 100L, mut_sd = 0.1)

      super$initialize(
        id = "local_search_2",
        param_set = param_set,
        param_classes = c("ParamLgl", "ParamInt", "ParamDbl", "ParamFct"),
        properties = c("dependencies", "single-crit"),   # FIXME: we cannot handle deps?
        label = "Local Search",
        man = "bbotk::mlr_optimizers_local_search"
      )
    }
  ),
  private = list(
    .optimize = function(inst) {
      ps = self$param_set
      psv = ps$values
      control = self$param_set$values
      control$obj_mult = inst$objective_multiplicator
      init_points = generate_design_random(inst$search_space, n = control$n_searches)$data
      .Call("c_local_search", inst$search_space, control, inst, init_points, PACKAGE = "bbotk")
    }
  )
)

mlr_optimizers$add("local_search", OptimizerBatchLocalSearch)
